# Welcome to Physics Programming!!

This is a **Physics Programming** tutorials for the <b><i>Physics lovers</i></b>.

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------

<br>

*Problem 1 :* 

#### A ball is dropped from a tower

The problem is as follows. A ball is dropped from a tower of height **h**. It has
initial velocity **zero** and accelerates downwards under **gravity**. The challenge
is to write a program that asks the user to enter the height in meters of the
tower and a time interval **t** in seconds, then prints on the screen the height of
the ball above the ground at time t after it is dropped, ignoring air resistance.

The steps involved are the following. First, we will use input statements
to get the values of h and t from the user. Second, we will calculate how far
the ball falls in the given time, using the standard kinematic formula **s = 1/2 gt<sup>2</sup>**,
where **g = 9.81 ms<sup>-2</sup>** is the acceleration due to gravity. Third, we print the
height above the ground at time t, which is equal to the total height of the
tower minus this value, or h − s.

Formulas used: 

$$Derivation$$

$$ a = g = 9.81{m/s^2}$$

$$ s = ut + {1\over2}at^2 $$

$$ s = ut + {1\over2}gt^2 $$

$$ s = {1\over2}gt^2 $$

In [9]:
h = float(input("Enter the height of the tower : "))
t = float(input("Enter the time interval : "))
s = (9.81*t**2)/2
print(s)
print("The height of the ball is : ",h - s,"m")

Enter the height of the tower : 100
Enter the time interval : 2
19.62
The height of the ball is :  80.38 m


*Problem 2 : *

A ball is again dropped from a tower of height h with initial velocity zero. Write a
program that asks the user to enter the height in meters of the tower and then calculates
and prints the time the ball takes until it hits the ground, ignoring air resistance. Use
your program to calculate the time for a ball dropped from a 100 m high tower.
 
Formulas used : 

$$ Value $$

$$ a = g = 9.81{m/s^2} $$

$$ Motion formula $$

$$ v^2 = u^2 + 2as $$
$$ v = u + at $$

$$Converting$$

$$ v^2 = u^2 + 2gs $$
$$ v^2 = 2gs $$

$$ v = gt$$


In [17]:
import math
h = float(input("Enter the height of the tower : "))
temp = 2*9.81*h
temp = math.sqrt(temp)
v = temp
# print(v)
t = v/9.81
print("The time taken to fall : ",t,"s")

Enter the height of the tower : 100
The time taken to fall :  4.515236409857309 s


### The **math** function 

<br>
<br>
There are many operations one might want to perform in a program that are
more complicated than simple arithmetic, such as multiplying matrices, calcu-
lating a logarithm, or making a graph. Python comes with facilities for doing
each of these and many other common tasks easily and quickly. These facil-
ities are divided into packages—collections of related useful things—and each
package has a name by which you can refer to it. For instance, all the standard
mathematical functions, such as logarithm and square root, are contained in a
package called math. Before you can use any of these functions you have to tell
the computer that you want to. For example, to tell the computer you want to
use the log function, you would add the following line to your program:

In [18]:
from math import log

In [20]:
x = log(2.5)
print(x)

0.9162907318741551


*Problem 3 :*


### Converting Polar Coordinates

Suppose the position of a point in two-dimensional space is given to us in polar
coordinates r, θ and we want to convert it to Cartesian coordinates x, y. How
would we write a program to do this? The appropriate steps are:
1. Get the user to enter the values of r and θ.

2. Convert those values to Cartesian coordinates using the standard formulas:

    x = r cos θ
    y = r sin θ
<br>

3. Print out the results.

Since the formulas involve the mathematical functions sin and cos we are
going to have to import those functions from the math package at the start of
the program. Also, the sine and cosine functions in Python (and in most other
computer languages) take arguments in radians. If we want to be able to enter
the angle θ in degrees then we are going to have to convert from degrees to
radians, which means multiplying by π and dividing by 180.
Thus our program might look something like this:

In [26]:
from math import sin,cos,pi

# Ask the user for the values of r and theta
r = float(input("Enter r: "))
d = float(input("Enter theta in degrees: "))

# Convert the angle to radians
theta = d*pi/180

# Calculate the equivalent Cartesian coordinates
x = r*cos(theta)
y = r*sin(theta)

# Print out the results
print("\n")
print("X = ",x,)
print("Y = ",y)

Enter r: 4
Enter theta in degrees: 60


X =  2.0000000000000004
Y =  3.4641016151377544


## ARRAYS

As we have seen, a list in Python is an ordered set of values, such as a set of
integers or a set of floats. There is another object in Python that is somewhat
similar, an array. An array is also an ordered set of values, but there are some
important differences between lists and arrays:

1. The number of elements in an array is fixed. You cannot add elements to an array once it is created, or remove them.
 

2. The elements of an array must all be of the same type, such as all floats or all integers. You cannot mix elements of different types in the same array and you cannot change the type of the elements once an array is created.

Lists, as we have seen, have neither of these restrictions and, on the face of
it, these seem like significant drawbacks of the array. Why would we ever
use an array if lists are more flexible? The answer is that arrays have several
significant advantages over lists as well:

3. Arrays can be two-dimensional, like matrices in algebra. That is, rather than just a one-dimensional row of elements, we can have a grid of them. Indeed, arrays can in principle have any number of dimensions, including three or more, although we won’t use dimensions above two in this book. Lists, by contrast, are always just one-dimensional.


4. Arrays behave roughly like vectors or matrices: you can do arithmetic with them, such as adding them together, and you will get the result you expect. This is not true with lists. If you try to do arithmetic with a list you will either get an error message, or you will not get the result you expect.


5. Arrays work faster than lists. Especially if you have a very large array with many elements then calculations may be significantly faster using an array.


In physics it often happens that we are working with a fixed number of elements all of the same type, as when we are working with matrices or vectors,for instance. In that case, arrays are clearly the tool of choice: the fact that we cannot add or remove elements is immaterial if we never need to do such a thing, and the superior speed of arrays and their flexibility in other respects can make a significant difference to our programs. We will use arrays extensively in this book—far more than we will use lists.

Before you use an array you need to create it, meaning you need to tell the
computer how many elements it will have and of what type. Python provides
functions that allow you do this in several different ways. These functions are
all found in the package numpy.

In the simplest case, we can create a one-dimensional array with n elements, all of which are initially equal to zero, using the function zeros fromthe numpy package. The function takes two arguments. The first is the number
of elements the array is to have and the second is the type of the elements,
such as int, float, or complex. For instance, to create a new array with four
floating-point elements we would do the following:


In [27]:
from numpy import zeros
a = zeros(4,float)
print(a)

[0. 0. 0. 0.]


To create a two-dimensional floating-point array with m rows and n columns, “zeros([m,n],float)”, so

In [29]:
a = zeros([3,4],float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Reading an array from file

In [31]:
from numpy import loadtxt
a = loadtxt('values.txt', float)
print(a)

[1. 2. 0. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
a = array([[1,2,3],[4,5,6]], int)
print(a.size)
print(a.shape)

6
(2, 3)


In [34]:
values = loadtxt('values.txt', float)
mean = sum(values)/len(values)
print(mean)

4.5
